import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

type PageKey = 'customers' | 'deliveries' | 'ai' | 'analytics' | 'integrations' | 'team' | 'settings';

@Component({
  selector: 'app-operations-page',
  template: `
    <section class="page-heading compact"><div><p class="eyebrow">{{ content().kicker }}</p><h1>{{ content().title }}</h1><p>{{ content().description }}</p></div><span class="phase-badge">{{ content().phase }}</span></section>
    <section class="feature-hero panel"><div class="feature-hero-copy"><span class="feature-symbol"><span class="nav-icon" [attr.data-icon]="content().icon"></span></span><span class="section-kicker">Prochaine capacité</span><h2>{{ content().headline }}</h2><p>{{ content().body }}</p><div class="feature-actions"><button class="primary-button" type="button" disabled>{{ content().action }}</button><span>Les contrôles restent désactivés jusqu’à la configuration réelle.</span></div></div><div class="feature-progress"><span>Fondation livrée</span><div><i [style.width.%]="content().progress"></i></div><strong>{{ content().progress }}%</strong></div></section>
    <section class="setup-grid">
      @for (step of content().steps; track step.title; let index = $index) { <article class="panel setup-card"><span class="step-number">0{{ index + 1 }}</span><div><h3>{{ step.title }}</h3><p>{{ step.text }}</p></div><span class="setup-state" [class.ready]="step.ready">{{ step.ready ? 'Prêt' : 'À configurer' }}</span></article> }
    </section>
  `,
})
export class OperationsPageComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly pages: Record<PageKey, { kicker: string; title: string; description: string; phase: string; icon: string; headline: string; body: string; action: string; progress: number; steps: { title: string; text: string; ready: boolean }[] }> = {
    customers: { kicker: 'Relation client', title: 'Clients', description: 'Retrouvez les profils et le contexte utile sans fusion risquée des identités.', phase: 'Étape 2', icon: 'users', headline: 'Une vue client liée aux conversations', body: 'La structure de données est prête. La prochaine étape relie profils, adresses, conversations et commandes dans une vue sécurisée.', action: 'Ajouter un client', progress: 45, steps: [{ title: 'Identité par canal', text: 'Chaque identité WhatsApp reste unique dans sa connexion.', ready: true }, { title: 'Historique commercial', text: 'Relier commandes et conversations au profil client.', ready: false }, { title: 'Consentement', text: 'Tracer la base de contact et les préférences.', ready: false }] },
    deliveries: { kicker: 'Dernier kilomètre', title: 'Livraisons', description: 'Préparez, soumettez et réconciliez chaque expédition sans doublon.', phase: 'Étape 5', icon: 'truck', headline: 'Choisir le premier transporteur tunisien', body: 'Le contrat d’adaptation est défini. Il faut confirmer COD, sandbox, couverture, suivi et idempotence avec un fournisseur réel.', action: 'Configurer un transporteur', progress: 25, steps: [{ title: 'Contrat interne', text: 'Création, tarif, suivi et annulation sont spécifiés.', ready: true }, { title: 'Accès sandbox', text: 'Documentation et identifiants du transporteur.', ready: false }, { title: 'Réconciliation', text: 'Empêcher un second colis après un timeout ambigu.', ready: false }] },
    ai: { kicker: 'Automatisation contrôlée', title: 'Agents IA', description: 'Configurez la voix commerciale sans céder l’autorité transactionnelle.', phase: 'Étape 3', icon: 'sparkles', headline: 'Sélectionner le modèle sur preuves', body: 'Nous testerons français, arabe, anglais et Derja, puis choisirons le modèle hébergé le moins cher qui respecte les seuils.', action: 'Lancer l’évaluation', progress: 30, steps: [{ title: 'Outils bornés', text: 'Prix, stock et commandes passent par le backend.', ready: true }, { title: 'Jeu multilingue', text: 'Constituer au moins 200 scénarios revus.', ready: false }, { title: 'Modèle et budget', text: 'Choisir la meilleure option gratuite ou économique.', ready: false }] },
    analytics: { kicker: 'Décisions', title: 'Analytiques', description: 'Mesurez la conversion, le temps de réponse et le coût sans métriques trompeuses.', phase: 'Étape 6', icon: 'chart', headline: 'Des indicateurs avec leurs dénominateurs', body: 'Les événements opérationnels alimenteront des cohortes de conversations, commandes et livraisons clairement définies.', action: 'Voir la méthodologie', progress: 20, steps: [{ title: 'Définitions KPI', text: 'Les formules et fenêtres sont documentées.', ready: true }, { title: 'Événements métier', text: 'Émettre les événements nécessaires au calcul.', ready: false }, { title: 'Cohortes matures', text: 'Éviter de conclure sur des livraisons incomplètes.', ready: false }] },
    integrations: { kicker: 'Écosystème', title: 'Intégrations', description: 'Connectez uniquement les services nécessaires au pilote.', phase: 'Décisions requises', icon: 'link', headline: 'Trois connexions pour le parcours complet', body: 'WhatsApp reçoit la demande, le modèle prépare une réponse fondée et le transporteur transforme une commande prête en livraison suivie.', action: 'Commencer la configuration', progress: 20, steps: [{ title: 'WhatsApp Cloud API', text: 'App Meta, compte WhatsApp, numéro et secrets webhook.', ready: false }, { title: 'Modèle IA', text: 'Option hébergée gratuite ou à coût très faible.', ready: false }, { title: 'Transporteur tunisien', text: 'API COD avec sandbox et suivi.', ready: false }] },
    team: { kicker: 'Collaboration', title: 'Équipe', description: 'Invitez les administrateurs et agents avec le minimum de privilèges.', phase: 'Étape 2', icon: 'users', headline: 'Des rôles simples et audités', body: 'Les adhésions et contrôles d’accès existent. Les invitations, MFA et sessions doivent être terminées avant le pilote.', action: 'Inviter un membre', progress: 40, steps: [{ title: 'Rôles', text: 'Administrateur et agent sont appliqués côté API.', ready: true }, { title: 'Invitations', text: 'Jetons uniques et expiration.', ready: false }, { title: 'MFA administrateur', text: 'TOTP et codes de récupération.', ready: false }] },
    settings: { kicker: 'Espace de travail', title: 'Paramètres', description: 'Centralisez identité, langues, règles et limites de votre entreprise.', phase: 'Étape 2', icon: 'settings', headline: 'Configurer le cadre de confiance', body: 'Les réglages définiront la devise TND, Africa/Tunis, les langues et les limites de consommation.', action: 'Modifier les paramètres', progress: 35, steps: [{ title: 'Devise et fuseau', text: 'TND et Africa/Tunis sont les valeurs initiales.', ready: true }, { title: 'Langues', text: 'Interface française et arabe avec RTL.', ready: false }, { title: 'Quotas', text: 'Budgets IA et volumes par entreprise.', ready: false }] },
  };
  protected readonly content = signal(this.pages.integrations);

  constructor() { this.route.data.subscribe((data) => this.content.set(this.pages[data['page'] as PageKey] ?? this.pages.integrations)); }
}
